M48
; DRILL file {KiCad 7.0.5} date Mon 19 Jun 2023 02:47:56 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-19T14:47:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X107.105Y-126.76
X107.105Y-132.54
T2
X102.46Y-136.484
X102.46Y-138.516
X107.54Y-137.5
T0
M30
